name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Asegúrate de utilizar la versión correcta de .NET

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -o build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/wwwroot       

    - name: Create .nojekyll file
      run: echo " " > ./build/wwwroot/.nojekyll

    - name: Create 404.html
      run: cp ./build/wwwroot/index.html ./build/wwwroot/404.html
